In [4]:
import numpy as np
import math

# 位置正解

In [5]:
LONG=40
WIDE=10

In [43]:
pi = 3.1415926

o1 = 0
o2 = -pi/2
o3 = -pi/2

l1 = 5
l2 = 20
l3 = 20

c1 = math.cos(o1)
s1 = math.sin(o1)
c2 = math.cos(o2)
s2 = math.sin(o2)
c3 = math.cos(o3)
s3 = math.sin(o3)

R_OA = np.array([[ 1 , 0 , 0 ,WIDE/2],
                 [ 0 , 1 , 0 ,LONG/2],
                 [ 0 , 0 , 1 ,0     ],
                 [ 0 , 0 , 0 ,1     ]])

R_AB = np.array([[ c1 , 0 , -s1 ,l1 ],
                 [ 0  , 1 , 0   ,0  ],
                 [ s1 , 0 , c1  ,0  ],
                 [ 0  , 0 , 0   ,1  ]])

R_BC = np.array([[ 1 , 0 , 0 ,0    ],
                 [ 0 , 1 , 0 ,c2*l2],
                 [ 0 , 0 , 1 ,s2*l2],
                 [ 0 , 0 , 0 ,1    ]])

R_CD = np.array([[ 1 , 0 , 0 ,0    ],
                 [ 0 , 1 , 0 ,c3*l3],
                 [ 0 , 0 , 1 ,s3*l3],
                 [ 0 , 0 , 0 ,1    ]])

R_AO = R_OA.T
R_BA = R_AB.T
R_CB = R_BC.T
R_DC = R_CD.T



In [54]:
s3*l3

-19.999999999999993

In [7]:
mind = [0,0,0,1]
R_OB = np.dot(R_OA,R_AB)
R_BD = np.dot(R_BC,R_CD)
R = np.dot(R_OB,R_BD)
print(np.dot(R,mind))


[ 10.          20.00000107 -40.           1.        ]


# 速度传递求解

In [12]:
w_Motor_A = [0,10,0,1]
w_Motor_B = [10,0,0,1]
w_Motor_C = [10,0,0,1]

sqare = np.array([[[0 ,0 ,0 ,0],
                   [0 ,0 ,-1,0],
                   [0 ,1 ,0 ,0],
                   [0 ,0 ,0 ,0]],
                  [[0 ,0 ,1 ,0],
                   [0 ,0 ,0 ,0],
                   [-1,0 ,0 ,0],
                   [0 ,0 ,0 ,0]],
                  [[0 ,-1,0 ,0],
                   [1 ,0 ,0 ,0],
                   [0 ,0 ,0 ,0],
                   [0 ,0 ,0 ,0]],
                  [[0 ,0 ,0 ,0],
                   [0 ,0 ,0 ,0],
                   [0 ,0 ,0 ,0],
                   [0 ,0 ,0 ,1]]])
sqare_T = sqare.T
w_sq_Motor_A = np.dot(sqare,w_Motor_A)
w_sq_Motor_B = np.dot(sqare,w_Motor_B)
w_sq_Motor_C = np.dot(sqare,w_Motor_C)
print(w_sq_Motor_A)
print(w_sq_Motor_B)
print(w_sq_Motor_C)

[[  0   0  10   0]
 [  0   0   0   0]
 [-10   0   0   0]
 [  0   0   0   1]]
[[  0   0   0   0]
 [  0   0 -10   0]
 [  0  10   0   0]
 [  0   0   0   1]]
[[  0   0   0   0]
 [  0   0 -10   0]
 [  0  10   0   0]
 [  0   0   0   1]]


In [9]:
w_B  = np.dot(R_BA,w_Motor_A)
#中间计算---------------------------
P_AB = np.dot(R_AB,[0,0,0,1])    #--
v_B_  = np.dot(w_sq_Motor_A,P_AB)#--
#-----------------------------------
v_B = np.dot(R_BA,v_B_)

print(w_B,v_B,v_B_)

w_C_ = np.dot([[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,0]],w_B+w_Motor_B)+[0,0,0,1]
w_C  = np.dot(R_CB,w_C_)
#中间计算---------------------------
P_BC = np.dot(R_BC,[0,0,0,1])    #--
v_C_  = np.dot(w_sq_Motor_B,P_BC)#--
#-----------------------------------
v_C = np.dot(R_CB,v_C_+v_B)

print(w_C,v_C,v_C_)

w_D_ = np.dot([[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,0]],w_C+w_Motor_C)+[0,0,0,1]
w_D  = np.dot(R_DC,w_D_)
#中间计算---------------------------
P_CD = np.dot(R_CD,[0,0,0,1])    #--
v_D_  = np.dot(w_sq_Motor_C,P_CD)#--
#-----------------------------------
v_D = np.dot(R_DC,v_D_+v_C)

print(w_D,v_D,v_D_)




[ 0. 10.  0.  1.] [  0.   0. -50.   1.] [  0.   0. -50.   1.]
[10.         10.          0.          1.00000536] [   0.          200.          -49.99999464 1002.        ] [0.00000000e+00 2.00000000e+02 5.35897932e-06 1.00000000e+00]
[20.         10.          0.          1.00000536] [   0.          400.          -49.99998928 2003.        ] [0.00000000e+00 2.00000000e+02 5.35897932e-06 1.00000000e+00]


# 静力传递求解

In [95]:
F_D = [3,1,2,1]
N_D = [0,0,0,1]

In [96]:
F_C = F_D
#中间计算-----------------------------
N_C_sqare = np.dot(sqare_T,F_D)    #--
N_C_ = N_D + np.dot(N_C_sqare,P_CD)#--
#-------------------------------------
N_C = np.dot([[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,0]],N_C_)+[0,0,0,1]

F_B = F_C
#中间计算-----------------------------
N_B_sqare = np.dot(sqare_T,F_C)    #--
N_B_ = N_C + np.dot(N_B_sqare,P_BC)#--
#-------------------------------------
N_B = np.dot([[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,0]],N_B_)+[0,0,0,1]

F_A = F_B
#中间计算-----------------------------
N_A_sqare = np.dot(sqare_T,F_B)    #--
N_A_ = N_B + np.dot(N_A_sqare,P_AB)#--
#-------------------------------------
N_A = np.dot([[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,0]],N_A_)+[0,0,0,1]

print(N_A,F_A)

[  40.00000214 -130.            4.99999678    1.        ] [3, 1, 2, 1]


# 加速度传递求解