In [1]:
import numpy as np

In [10]:
sqare = np.array([[[0 ,0 ,0 ],
                   [0 ,0 ,-1],
                   [0 ,1 ,0 ]],
                  [[0 ,0 ,1 ],
                   [0 ,0 ,0 ],
                   [-1,0 ,0 ]],
                  [[0 ,-1,0 ],
                   [1 ,0 ,0 ],
                   [0 ,0 ,0 ]]])        

In [5]:
#力向量
F1 = np.array([1,2,3]) 
F2 = np.array([1,0,0]) 
F3 = np.array([1,0,0]) 
F4 = np.array([1,0,0]) 

In [6]:
#位置向量
P1 = np.array([1,1,0]) 
P2 = np.array([1,-1,0]) 
P3 = np.array([-1,1,0]) 
P4 = np.array([-1,-1,0])

### 从足端力到质点力的运算

In [7]:
O1_W = np.cross(P1,F1)
O2_W = np.cross(P2,F2)
O3_W = np.cross(P3,F3)
O4_W = np.cross(P4,F4)
O_W = O1_W + O2_W + O3_W + O4_W

In [8]:
iny = np.array([[1,0,0],[0,1,0],[0,0,1]])
O1_F = np.dot(iny,F1)
O2_F = np.dot(iny,F2)
O3_F = np.dot(iny,F3)
O4_F = np.dot(iny,F4)
O_F = O1_F + O2_F + O3_F + O4_F

In [9]:
print(O_W,O_F)

[ 3 -3  2] [4 2 3]


### 从质点力到足端力的解耦

### 我是分割线-------------------------------------------------------------------------------------------------------------------------------------------------

#### 计算广义逆矩阵（机体坐标系到各个足端）

In [11]:
k1_W = np.dot(sqare,P1)
k2_W = np.dot(sqare,P2)
k3_W = np.dot(sqare,P3)
k4_W = np.dot(sqare,P4)
k_W = np.concatenate((k1_W,k2_W,k3_W,k4_W),axis=1)
k_W

array([[ 0,  0,  1,  0,  0, -1,  0,  0,  1,  0,  0, -1],
       [ 0,  0, -1,  0,  0, -1,  0,  0,  1,  0,  0,  1],
       [-1,  1,  0,  1,  1,  0, -1, -1,  0,  1, -1,  0]])

In [12]:
k_F = np.array([[1,0,0,1,0,0,1,0,0,1,0,0],
                [0,1,0,0,1,0,0,1,0,0,1,0],
                [0,0,1,0,0,1,0,0,1,0,0,1]])
k = np.concatenate((k_F,k_W),axis=0)
k

array([[ 1,  0,  0,  1,  0,  0,  1,  0,  0,  1,  0,  0],
       [ 0,  1,  0,  0,  1,  0,  0,  1,  0,  0,  1,  0],
       [ 0,  0,  1,  0,  0,  1,  0,  0,  1,  0,  0,  1],
       [ 0,  0,  1,  0,  0, -1,  0,  0,  1,  0,  0, -1],
       [ 0,  0, -1,  0,  0, -1,  0,  0,  1,  0,  0,  1],
       [-1,  1,  0,  1,  1,  0, -1, -1,  0,  1, -1,  0]])

In [13]:
K= np.matrix(k)
K.I

matrix([[ 2.50000000e-01,  0.00000000e+00,  0.00000000e+00,
          3.85185989e-34,  6.93889390e-18, -1.25000000e-01],
        [ 0.00000000e+00,  2.50000000e-01,  0.00000000e+00,
         -3.85185989e-34, -6.93889390e-18,  1.25000000e-01],
        [ 0.00000000e+00,  0.00000000e+00,  2.50000000e-01,
          2.50000000e-01, -2.50000000e-01,  1.06549069e-17],
        [ 2.50000000e-01,  0.00000000e+00,  0.00000000e+00,
         -3.85185989e-34, -6.93889390e-18,  1.25000000e-01],
        [ 0.00000000e+00,  2.50000000e-01,  0.00000000e+00,
         -3.85185989e-34, -6.93889390e-18,  1.25000000e-01],
        [ 0.00000000e+00,  0.00000000e+00,  2.50000000e-01,
         -2.50000000e-01, -2.50000000e-01, -4.49525344e-17],
        [ 2.50000000e-01,  0.00000000e+00,  0.00000000e+00,
          3.85185989e-34,  6.93889390e-18, -1.25000000e-01],
        [ 0.00000000e+00,  2.50000000e-01,  0.00000000e+00,
          3.85185989e-34,  6.93889390e-18, -1.25000000e-01],
        [ 0.00000000e+00,  0.000

### 我是分割线-------------------------------------------------------------------------------------------------------------------------------------------------

In [16]:
want = np.array([0,0,8,0,0,2])

In [17]:
np.dot(K.I,want)

matrix([[-0.25,  0.25,  2.  ,  0.25,  0.25,  2.  , -0.25, -0.25,  2.  ,
          0.25, -0.25,  2.  ]])

### 关节力矩向足端力矢量的运算

In [ ]:
foot_want = np.array([0,0,8,0,0,2])

### 足端力向关节力的解耦